server:
        port: 8080
        servlet:
                context-path: /api/v1

spring:
        # --- AJOUT POUR IGNORER RABBITMQ AU DÉMARRAGE ---
        autoconfigure:
                exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
        # CHOIX DU PROFIL-----------------------------------------------
        profiles:
                active : prod
        #EVENT HANDLING-----------------------------------------------
        modulith:
                events:
                        jdbc-schema-initialization: true
                republish-outstanding-events-on-restart: true

# --- DÉSACTIVER LE CHECK DE SANTÉ RABBIT ---
management:
        health:
                rabbit:
                        enabled: false

springdoc:
        swagger-ui:
                path: /swagger-ui.html
        api-docs:
                path: /v3/api-docs
        packages-to-scan: com.app.user.api, com.app.task.api