# application-prod.yml
server:
        port: ${PORT:8080}  # Render injecte PORT automatiquement

spring:
        datasource:
                url: ${SPRING_DATASOURCE_URL}           # Render injecte ça
                username: ${SPRING_DATASOURCE_USERNAME}
                password: ${SPRING_DATASOURCE_PASSWORD}
                driver-class-name: org.postgresql.Driver
        jpa:
                hibernate:
                        ddl-auto: update
                show-sql: false
                database-platform: org.hibernate.dialect.PostgreSQLDialect
        h2:
                console:
                        enabled: false

# Logging plus léger en prod
logging:
        level:
                root: INFO
                org.springframework: INFO
                com.app: INFO

# Désactiver Swagger en prod si tu veux
springdoc:
        swagger-ui:
                enabled: false